version: '3'

services:

  dev:
    container_name: dev
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/home/vscode/miniproj/
      - ${HOME}/.vscode-server/extensions/:/home/vscode/.vscode-server/extensions/

  postgres:
    container_name: postgres
    image: public.ecr.aws/docker/library/postgres:15.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - '5432'
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
